version: '3.8'

services:
  backend:
    build: ./backend
    container_name: flask-api
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: react-app
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped